# Generated by Django 3.1.7 on 2021-04-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210406_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.theme', verbose_name='Тема'),
        ),
    ]
